permalink: /:year:month/:title
markdown: redcarpet
redcarpet:
  extensions: [autolink, fenced_code_blocks, no_intra_emphasis, smart, strikethrough, superscript, tables]
highlighter: rouge
url: http://r.oktas.us
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: roktas
archive: Son Girdiler
assets: /assets
author: Recai Oktaş
disqus: roktas
email: roktas@bil.omu.edu.tr
facebook: https://facebook.com/roktas
feed: http://feeds.feedburner.com/roktas
flickr: ~
google: ~
googleanalyticsid: UA-30559967-2
googleplus: +RecaiOktaş
gpg: 72BB 34DF 2B9D 0E3A
keybase: https://keybase.io/roktas
domain: r.oktas.us
logo: /assets/57/57-normal-128x128.png
organization: 19
picasa: ~
related: Diğer Girdiler
repository: roktas.github.io
ribbon: ~
title: Recai Oktaş
twitter: http://twitter.com/roktas

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
